### ISSUE TITLE
Le ballon ne va pas assez vite

### ISSUE THREAD

**Issue by Baptiste-mrch** [Lurius-tharn/RCQ_Arcade#14]
Dans le premier jeu (type "Donkey Kong"), le ballon ne va pas assez vite, ce qui a pour conséquence que le joueur n'a pas le temps d'aller à l'autre bout de l'écran pour chopper le ballon
Idéalement, il faudrait que le joueur puisse aller d'un bout à l'autre de l'écran pour chopper le ballon qui tombe a l'opposé

Les ballons doivent quand même s'accélérer dans le temps

**Comment by Lurius-tharn** [comment]
Retours pris en compte: J'ai augmenté la vitesse des balles, et augmenté la vitesse du joueur? Je pense implémenter un system de dash ( Le person va a l'autre bout de la scene en appuyant sur un bouton

**Comment by Baptiste-mrch** [comment]
Je ne sais pas si ça peut être simple pour un jeu d'enfant, à réfléchir mais ça peut être une bonne idée

**Comment by Lurius-tharn** [comment]
pour l'instant, impossible d'augmenter la vitesse du joueur
